### ISSUE TITLE
Enable rendering to PDF

### ISSUE THREAD

**Issue by ThomUK** [ThomUK/SPCreporter#1]
Enable an option to render to PDF, with accordions in open position.
Find a sane way to handle page-breaking in PDF version (split to another issue if this is a big job).

**Comment by francisbarton** [comment]
I have this code for PDF creation in my maternity reporting package:

```
#' Convert SPCreporter's HTML output to PDF
#' @param filepath. A file path to the HTML file
#' @export
convert_to_pdf <- function(filepath) {
  out_path <- file.path(tempdir(), basename(filepath))
  pdf_path <- xfun::with_ext(filepath, "pdf")
  filepath |>
    readr::read_file() |>
    stringr::str_replace_all("<details>", "<details open>") |>
    readr::write_file(out_path)
  pagedown::chrome_print(out_path, pdf_path)
  usethis::ui_info("PDF created at {pdf_path}")
  invisible(TRUE)
}
```

In terms of page breaks, my latest thinking is to create a landscape PDF with a single chart per page / a page break after each chart. But I haven't done any code for this yet. The landscape setup could be in the YAML header. It might be easier in Quarto than in Rmd - you can really easily add in page breaks in Quarto for PDF/Word that will be ignored in the HTML output (of course). Or you can do it with CSS I think.
