### ISSUE TITLE
Example data (config files) need to have a measure_prefix column?

### ISSUE THREAD

**Issue by francisbarton** [ThomUK/SPCreporter#103]
Tests for `spcr_make_data_bundle()`, for example, currently run using the example data as the basis for the tests. Either need to write different tests using tribble data in the test file, (and/)or edit the Excel files and re-import into package data.

**Comment by ThomUK** [comment]
Closing this, as the "ref" column uniquely identifies each metric (which is different to the naming of some NUH internal code).  
Feel free to re-open with more details if I have misunderstood the issue.
