### ISSUE TITLE
Example config .xlsx file missing essential columns

### ISSUE THREAD

**Issue by francisbarton** [ThomUK/SPCreporter#25]
`spcr_make_report()` expects to find variables for `Reviewed_At` and `Escalated_To` now. I think these need adding as extra columns in the measure_config example file?

**Comment by ThomUK** [comment]
I *think* I managed to make those columns optional to avoid breaking other peoples' code.  If they appear in the dataframe being passed in, they are used, but if not the code assigns NA and later functions ignore them.  Can you see any problems with this implementation?

https://github.com/ThomUK/SPCreporter/blob/36372b31fa26c9516e1093e166a6d75a87956807/R/spcr_calculate_row.R#L31-L32

The capability definitely needs documenting.  Perhaps a gh-pages site with a vignette?
