### ISSUE TITLE
Multiple rebase dates cause duplicate outputs in report

### ISSUE THREAD

**Issue by francisbarton** [ThomUK/SPCreporter#33]
`spcr_calculate_row()` calls `spcr_parse_rebase_dates()`. This returns a vector (eg of length 2 in this case) hence calculate_row then creates two rows in the tibble that it outputs.

Solution is to keep the combined (length 1) vector for the output tibble, but use the parsed (length > 1 in this case) vector to pass to the rebase argument of `NHSRplotthedots::ptd_spc()`.

Patch incoming!

**Comment by ThomUK** [comment]
Temporarily fixed by merging #34.  We'll leave this issue open until we have some tests in place.
