### ISSUE TITLE
Reduce file size of finished html output

### ISSUE THREAD

**Issue by ThomUK** [ThomUK/SPCreporter#38]
The file size of finished reports can be large.  Rmd includes some elements in the html output which are not required.  
Remove these (for example <script> tags)

**Comment by francisbarton** [comment]
Reducing the image quality of the charts, from 1800x900px to 1500x750px, reduces the report from 16MB to 14MB. Removing all the <script> sections removes a further 0.7MB.
I think reducing the chart image resolution further would make it start to look a little fuzzy.
